services:
  postgres-inventory:
    image: postgres:17.6-alpine3.22
    environment:
      - 'POSTGRES_DB=inventory-db'
      - 'POSTGRES_USER=inventory-user'
      - 'POSTGRES_PASSWORD=pA33w0Rd'
    ports:
      - '5432:5432'
    volumes:
      - ./inventory-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory-user -d inventory-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  liquibase-test:
    image: liquibase/liquibase:4.27
    depends_on:
      postgres-inventory:
        condition: service_healthy
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://postgres-inventory:5432/inventory-db
      - LIQUIBASE_COMMAND_USERNAME=inventory-user
      - LIQUIBASE_COMMAND_PASSWORD=pA33w0Rd
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=db.changeLog.xml
      - LIQUIBASE_SEARCH_PATH=changelog,scripts
      - USER=liquibase
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
      - ./liquibase/scripts:/liquibase/scripts
    command:
      - "update"
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 2s
      retries: 3
    command: ["start-dev", "--http-port", "7080", "--import-realm"]
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    ports:
      - "7080:7080"

