spring.application.name=inventory

# R2DBC Configuration
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/inventory-db
spring.r2dbc.username=inventory-user
spring.r2dbc.password=pA33w0Rd

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:7080/realms/inventory-dev
clientId: inventory